# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-112060364-1'

menu:
  - name: 'CV'
    url: 'cv.html'
  - name: 'Publications'
    url: 'publications.html'
  - name: 'Cuurent Research'
    url: 'currentresearch.html'
  - name: 'People'
    url: 'presentations.html'
  - name: 'Art & Science'
    url: 'artandscience.html'
  - name: 'Contact'
    url: 'contact.html'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/JustinCLuong?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/justinluong/'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UC-3p5ABk3vPzAE80evNdfYg'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Justin-Luong'}
- {icon: 'envelope', link: 'mailto:jcl161@humboldt.edu'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
 
